server:
  port: 9006
  
spring:
  application:
    name: wechat-service-filesystem
  datasource:
    druid:
      url: jdbc:mysql://192.168.43.163:3306/wechat_filesystem?characterEncoding=utf-8
      username: root
      password: 123456
      driverClassName: com.mysql.jdbc.Driver
      initialSize: 5  #初始建立连接数量
      minIdle: 5  #最小连接数量
      maxActive: 20 #最大连接数量
      maxWait: 10000  #获取连接最大等待时间，毫秒
      testOnBorrow: true #申请连接时检测连接是否有效
      testOnReturn: false #归还连接时检测连接是否有效
      timeBetweenEvictionRunsMillis: 60000 #配置间隔检测连接是否有效的时间（单位是毫秒）
      minEvictableIdleTimeMillis: 300000  #连接在连接池的最小生存时间（毫秒）
  aop:
    auto: true
fdfs: 
  connect_timeout_in_seconds: 30
  network_timeout_in_seconds: 30
  fdfs_server_host: 192.168.43.163:22122
  image_max: 2000000
  image_types: jpg,jepg,png,gif

hadoop: 
  hdfsURI: hdfs://192.168.43.163:9000
  hadoop_home_dir: C://Users//Kim//Downloads//hadoop-3.2.1

eureka: 
  client: #客户端注册进eureka服务列表内
    service-url: 
      defaultZone: http://localhost:9000/eureka/
       #defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/      
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true     #访问路径可以显示IP地址    